package arcana;
/** DeckData.java — raw 78-card Rider-Waite deck data, ported from js/deck.js */
final class DeckData {
    private DeckData() {}

    // Each major: { name, meaning, symbol, lesson, reversedMeaning, reversedLesson }
    // manually entered the reverse meanings (short summary) into each stored array
    static final String[][] MAJORS = {
        { "0 · The Fool",
            "new beginnings and a leap of faith",
            "☀",
            "The Fool stands at the edge of a cliff, about to step into the unknown with total trust. It represents fresh starts, spontaneity, and the courage to begin before you feel ready. In a reading, it often asks whether you are embracing possibility or hesitating out of fear. Beginners should remember: the Fool is numbered zero because every journey in the deck starts here.",
            "recklessness, fear of change, and poor judgment",
            "When reversed, the Fool warns against leaping without looking. It can signal naivety, poor planning, or a paralysing fear of taking any risk at all. In a reading it often asks whether spontaneity has tipped into recklessness, or whether fear is disguising itself as caution. The lesson reversed: look before you leap." },
        { "I · The Magician",
            "willpower and manifesting your intentions",
            "∞",
            "The Magician has all four suit symbols on his table — he has every tool he needs, and so do you. This card is about focused willpower, skill, and turning intention into action. When it appears, it suggests the resources for success are already within reach. Learners often pair it with the question: what am I capable of that I have not yet used?",
            "manipulation, untapped potential, and misdirected energy",
            "Reversed, the Magician suggests skills are being misused or left undeveloped. It can point to self-doubt blocking action, or to someone using their talents manipulatively. Trickery, illusion, and wasted ability are common themes. The question to ask: are you using your abilities honestly and to their full potential?" },
        { "II · The High Priestess",
            "intuition and hidden knowledge",
            "☽",
            "The High Priestess sits between two pillars, guarding what cannot be learned from books. She represents intuition, mystery, and knowledge that surfaces only in stillness. In a spread she often advises waiting, listening, and trusting your inner voice over outside noise. She teaches new readers that not every answer is meant to be reasoned out.",
            "secrets withheld, disconnection from intuition, and repressed feelings",
            "Reversed, the High Priestess suggests you may be ignoring your inner voice or that hidden information is being deliberately withheld. It can also point to information overload drowning out genuine instinct. Something below the surface is being suppressed. The lesson reversed: silence is harder to find, but more necessary than ever." },
        { "III · The Empress",
            "nurturing, abundance and growth",
            "♀",
            "The Empress embodies nurturing energy, creativity, and natural abundance. She signals a fertile period — for projects, relationships, or self-care — where growth comes from tending rather than forcing. In readings she often points to the need to nourish something patiently. Think of her as the garden: things flourish when given warmth and time.",
            "dependence, creative block, and smothering energy",
            "Reversed, the Empress can indicate a creative block, neglect of self-care, or nurturing that has become smothering rather than supportive. Abundance may feel out of reach, or growth may have stalled from a lack of attention. It can also signal over-reliance on others. The lesson reversed: tend to yourself before you can tend to others." },
        { "IV · The Emperor",
            "structure, authority and stability",
            "♂",
            "The Emperor represents structure, discipline, and dependable leadership. Where the Empress grows, the Emperor builds — rules, boundaries, and order that protect what matters. In a reading he can point to authority figures or the need to take charge responsibly. Learners should notice whether his structure feels supportive or rigid in context.",
            "rigidity, abuse of power, and excessive control",
            "Reversed, the Emperor's structure becomes a cage. It can point to an authority figure who is controlling, domineering, or inflexible, or to a personal tendency to rule through fear rather than wisdom. It may also signal an inability to establish order where it is needed. The lesson reversed: power used without empathy corrupts what it was meant to protect." },
        { "V · The Hierophant",
            "tradition, learning and guidance",
            "⚭",
            "The Hierophant is the teacher of the deck, linked to tradition, institutions, and shared belief. He often appears when guidance from a mentor, established path, or conventional wisdom is relevant. He can also ask whether following tradition serves you or holds you back. For students of tarot, he is a reminder that learning systems exist for a reason.",
            "rebellion, unconventional paths, and challenging dogma",
            "Reversed, the Hierophant invites you to question the rules you have inherited. It can signal a desire to break from tradition, forge your own spiritual path, or reject institutions that no longer serve you. It can also indicate unconventional thinking being suppressed. The lesson reversed: sometimes wisdom means writing your own rules." },
        { "VI · The Lovers",
            "choice, union and alignment of values",
            "❦",
            "The Lovers is about far more than romance — it is the card of meaningful choice and alignment of values. It appears when a decision requires your head and heart to agree. In relationship questions it speaks to union and honesty; in others, to choosing what you truly stand for. Its lesson: real commitment begins with knowing yourself.",
            "misalignment, poor choices, and disharmony in relationships",
            "Reversed, the Lovers points to a relationship or decision that feels out of alignment. Values may conflict, communication may have broken down, or a choice may be being avoided out of fear. It can also signal an imbalance between self-love and love for others. The lesson reversed: you cannot truly unite with another until you are united within yourself." },
        { "VII · The Chariot",
            "determination and victory through focus",
            "⛨",
            "The Chariot shows two opposing forces harnessed by a single determined driver. It represents willpower, momentum, and victory achieved through focus and self-discipline. In readings it encourages pushing forward while keeping conflicting impulses under control. New readers can remember it as: success by steering, not by luck.",
            "lack of direction, aggression, and loss of control",
            "Reversed, the Chariot's opposing forces are no longer harnessed — they pull in different directions. It can signal a loss of motivation, a project stalling, or aggression replacing discipline. Control may be slipping internally or externally. The lesson reversed: speed without direction is just chaos in motion." },
        { "VIII · Strength",
            "courage and gentle inner power",
            "∞",
            "Strength depicts a figure calmly closing a lion's mouth — power expressed through gentleness, not force. It represents courage, patience, and mastering your own impulses. In a spread it often validates quiet persistence over dramatic action. Its teaching moment: true strength looks calm from the outside.",
            "self-doubt, weakness, and loss of inner resolve",
            "Reversed, Strength suggests that self-doubt or fear is overpowering the quieter voice of inner courage. Raw impulses may be winning over patience, or strength may be expressed through aggression rather than calm. It can also indicate exhaustion from suppressing emotions for too long. The lesson reversed: courage is not the absence of fear, it is acting despite it." },
        { "IX · The Hermit",
            "reflection and searching for truth",
            "✧",
            "The Hermit withdraws from the noise to seek truth by his own lantern. This card signals reflection, solitude, and inner searching. It often appears when the answer requires stepping back rather than gathering more opinions. Learners should read it as an invitation, not an isolation sentence.",
            "isolation, loneliness, and withdrawal from the world",
            "Reversed, the Hermit's healthy solitude has tipped into isolation. It can signal someone withdrawing out of fear rather than wisdom, or returning to the world before inner work is complete. It may also point to rejecting the guidance of others when it is genuinely needed. The lesson reversed: solitude heals, but isolation harms — know the difference." },
        { "X · Wheel of Fortune",
            "cycles, change and turning points",
            "☸",
            "The Wheel of Fortune reminds us that life moves in cycles — what is up will come down, and what is down will rise. It marks turning points, luck, and forces beyond personal control. In readings it asks how you respond to change you did not choose. Its core lesson for beginners: read the cards around it to see which way the wheel is turning.",
            "resistance to change, bad luck, and clinging to the past",
            "Reversed, the Wheel of Fortune suggests resistance to the natural cycles of life. Luck may feel persistently poor, or change may be being fought rather than embraced. It can also signal a repeated pattern that keeps returning because its lesson has not been learned. The lesson reversed: what you resist, persists." },
        { "XI · Justice",
            "fairness, truth and accountability",
            "⚖",
            "Justice holds the scales and the sword: fairness, truth, and consequences. It appears in questions of decisions, accountability, and cause-and-effect. It often signals that outcomes will match actions taken. For learners, Justice is a prompt to ask what an honest weighing of the situation reveals.",
            "injustice, dishonesty, and avoidance of accountability",
            "Reversed, Justice warns that fairness is not being served — either in a situation you are facing or in your own actions. It can point to dishonesty, bias, or a refusal to accept the consequences of past decisions. It may also indicate legal complications or a system that is failing you. The lesson reversed: avoiding accountability only delays the reckoning." },
        { "XII · The Hanged Man",
            "pause and seeing from a new angle",
            "⌇",
            "The Hanged Man hangs upside down voluntarily — and gains a new perspective for it. This card represents pause, surrender, and the insight that comes from stopping the struggle. It often appears when pushing harder will not help but reframing will. Its question to the querent: what would this look like from the other way up?",
            "stalling, resistance to surrender, and martyrdom",
            "Reversed, the Hanged Man suggests the pause has gone on too long or is being resisted entirely. It can signal stalling without growth, a refusal to see a situation differently, or playing the martyr without the accompanying wisdom. Sacrifice may be happening without purpose. The lesson reversed: suspension only transforms when you let go of the need to escape it." },
        { "XIII · Death",
            "endings and transformation",
            "✕",
            "Death is the most misread card in the deck: it almost never means literal death. It marks endings that make transformation possible — a chapter closing so another can open. In readings it asks what must be released for growth to happen. Beginners should learn to greet it as change, not doom.",
            "resistance to endings, stagnation, and fear of change",
            "Reversed, Death suggests an ending that is being resisted or a transformation that is overdue. Something that should have concluded is being held onto out of fear, resulting in stagnation. It can also signal a slow grinding change that refuses to complete itself. The lesson reversed: clinging to what is already gone prevents anything new from arriving." },
        { "XIV · Temperance",
            "moderation and blending opposites",
            "△",
            "Temperance blends water between two cups — patience, moderation, and the art of combining opposites. It appears when balance, timing, and gradual progress serve better than extremes. In a spread it often calms a heated situation. Its lesson: mastery is mixing, not choosing sides.",
            "imbalance, excess, and lack of long-term vision",
            "Reversed, Temperance points to imbalance in some area of life — excess, impatience, or a tendency to go to extremes rather than finding the middle path. Healing may be delayed because the conditions for it are not being created. Conflict between opposing forces may be going unmanaged. The lesson reversed: what cannot be blended will eventually break." },
        { "XV · The Devil",
            "attachment and restrictive patterns",
            "⛧",
            "The Devil shows figures in chains loose enough to remove — bondage that is partly chosen. It represents attachment, temptation, and restrictive patterns like habits or unhealthy dynamics. In readings it asks what you feel trapped by and what role you play in staying. Its empowering secret: the chains can come off.",
            "breaking free, releasing unhealthy bonds, and reclaiming power",
            "Reversed, the Devil is one of the more positive reversals in the deck. It signals the beginning of breaking free from an addiction, toxic relationship, or limiting belief. Awareness of what has been holding you back is dawning. The chains are being recognised and loosened. The lesson reversed: the first step to freedom is seeing the bars of the cage." },
        { "XVI · The Tower",
            "sudden upheaval and revelation",
            "⚡",
            "The Tower is sudden upheaval: a structure built on shaky foundations struck down in a flash of truth. It represents disruption, revelation, and the collapse of what was false. Though jarring, it clears ground for something honest to be rebuilt. Learners should note the cards after it — they show what rises from the rubble.",
            "avoiding disaster, delayed collapse, and fear of necessary change",
            "Reversed, the Tower suggests a disaster is being narrowly avoided, or that an inevitable collapse is being delayed through avoidance. The upheaval may be internal rather than external — a private revelation that has not yet been acted upon. It can also signal prolonged chaos with no resolution in sight. The lesson reversed: delaying the fall only makes the rubble deeper." },
        { "XVII · The Star",
            "hope, healing and renewed faith",
            "✦",
            "The Star follows the Tower for a reason: after upheaval comes healing. It represents hope, renewal, and quiet faith in the future. In readings it is a gentle green light — recovery is underway even if progress feels slow. It teaches that inspiration returns when we stop bracing.",
            "lost hope, disconnection, and lack of faith in the future",
            "Reversed, the Star suggests that hope has dimmed or faith in a positive outcome has been lost. Healing may feel inaccessible, or inspiration may have dried up. It can also signal placing too much hope in an outcome rather than trusting the process. The lesson reversed: faith does not require certainty — it only requires not giving up." },
        { "XVIII · The Moon",
            "uncertainty, dreams and illusion",
            "☾",
            "The Moon lights a path that is half-real, half-illusion. It represents uncertainty, dreams, fears, and things not yet clearly seen. In a spread it cautions against decisions made on incomplete or distorted information. Its advice to readers: wait for daylight, or look again.",
            "confusion lifting, deception revealed, and fears releasing",
            "Reversed, the Moon can indicate that a fog of confusion is beginning to lift and hidden truths are becoming clearer. Deception may be coming to light. However it can also signal that fears and anxieties are intensifying and becoming harder to manage. The lesson reversed: when the illusion fades, you must be ready to see what was always there." },
        { "XIX · The Sun",
            "joy, clarity and success",
            "☀",
            "The Sun is one of the most positive cards in the deck: joy, vitality, clarity, and success. It signals that what was hidden is now visible and warmth is returning. In readings it affirms confidence and celebration. Even beginners can trust it: the Sun rarely complicates a message.",
            "temporary setbacks, blocked joy, and excessive optimism",
            "Reversed, the Sun dims slightly but does not go out. It can point to a delay in success, a temporary loss of confidence, or optimism that has become unrealistic. Joy may feel harder to access than usual, or external circumstances may be clouding an otherwise positive situation. The lesson reversed: the sun is still there behind the clouds — this is temporary." },
        { "XX · Judgement",
            "awakening and answering a calling",
            "♪",
            "Judgement is the trumpet call of awakening — a summons to rise, evaluate your past, and answer a calling. It represents reckoning, forgiveness, and stepping into a truer version of yourself. In readings it often marks a moment of no-going-back clarity. Its question: what is calling you, and are you answering?",
            "self-doubt, ignoring the call, and fear of self-evaluation",
            "Reversed, Judgement suggests the call to awakening is being ignored or actively avoided. Self-doubt may be preventing honest self-evaluation, or past mistakes are not being forgiven and released. The reckoning is overdue. The lesson reversed: you cannot move into who you are becoming while refusing to look honestly at who you have been." },
        { "XXI · The World",
            "completion and wholeness",
            "◯",
            "The World is the final card of the Major Arcana: completion, wholeness, and integration. It appears when a cycle genuinely finishes — a graduation, an achievement, a chapter fully lived. In readings it celebrates arrival while hinting the next journey begins at the Fool again. It teaches that endings done well are their own reward.",
            "incompletion, loose ends, and delayed closure",
            "Reversed, the World suggests a cycle is close to completing but something is preventing full closure. Loose ends remain unresolved, or success feels hollow because an important step was skipped. There may be a reluctance to finish because finishing means facing what comes next. The lesson reversed: a journey left incomplete cannot become the foundation for the next one." },
    };

    static final String[] SUITS = {
        "Wands",
        "Cups",
        "Swords",
        "Pentacles"
    };

    static final String[] SUIT_SYMS = {
        "|",
        "∪",
        "†",
        "◆"
    };

    static final String[] SUIT_THEMES = {
        "energy and passion",
        "emotion and relationships",
        "thought and truth",
        "work and the material world"
    };

    static final String[] SUIT_LESSONS = {
        "Wands carry the fire element: creativity, ambition, and the spark that starts things.",
        "Cups carry the water element: feelings, connection, and the currents beneath the surface.",
        "Swords carry the air element: intellect, conflict, and truths that cut both ways.",
        "Pentacles carry the earth element: work, money, health, and tangible results."
    };

    static final String[] RANKS = {
        "Ace",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine",
        "Ten",
        "Page",
        "Knight",
        "Queen",
        "King"
    };

    static final String[] RANK_THEMES = {
        "a fresh seed of",
        "a choice within",
        "teamwork in",
        "stability within",
        "conflict within",
        "recovery in",
        "perseverance in",
        "mastery in",
        "nearing fulfilment of",
        "completion of",
        "curious exploration of",
        "bold pursuit of",
        "mature command of",
        "seasoned leadership over"
    };

    static final String[] RANK_LESSONS = {
        "Aces are pure beginnings — the suit's energy in seed form, full of potential.",
        "Twos introduce duality: choices, balances, and partnerships forming.",
        "Threes show first results: collaboration and early growth taking shape.",
        "Fours bring stability — rest, consolidation, and sometimes stagnation.",
        "Fives disrupt: conflict, loss, or challenge that tests the suit's energy.",
        "Sixes restore: recovery, generosity, and movement past difficulty.",
        "Sevens assess: patience, strategy, and re-evaluating the path.",
        "Eights accelerate: skill, movement, and dedicated effort.",
        "Nines approach the peak: near-fulfilment with one final lesson.",
        "Tens complete the cycle: the suit's energy fully realized, for better or worse.",
        "Pages are students of their suit — curious, inexperienced, eager to learn.",
        "Knights act on their suit — driven, sometimes reckless, always in motion.",
        "Queens embody their suit inwardly — mature, intuitive command of its energy.",
        "Kings direct their suit outwardly — seasoned authority and responsibility."
    };
    
    // reversed meanings for the minors
    static final String[] RANK_REVERSED = {
        "blocked potential and missed opportunities",
        "imbalance and indecision",
        "lack of teamwork and missed connections",
        "stagnation and rigidity",
        "avoiding conflict and refusing to learn from loss",
        "stalled recovery and unresolved issues",
        "self-doubt and lack of persistence",
        "scattered energy and lack of direction",
        "anxiety and near-completion that stalls",
        "burdens of completion and failure to move on",
        "immaturity and lack of focus",
        "recklessness and scattered pursuit",
        "neglect and emotional withdrawal",
        "abuse of authority and poor leadership"
    };

}
